apiVersion: v1
kind: Pod
metadata:
  name: secret-demo
spec:
  containers:
    - name: secret-container
      image: nginx
      volumeMounts:
        - name: secret
          readOnly: true
          mountPath: /etc/secret
  volumes:
    - name: secret
      secret:
        secretName: secretfile
